
---
title: "**PM<sub>10</sub> from the Monitoring Stations and Satellite readings in the UAE**"
output:
  html_document:
    fig_height: 2.5
    fig_width: 9.5
    theme: flatly
---

```{r set_up, message = FALSE, echo = FALSE, warning = FALSE}
library(threadr)
library(dygraphs)
library(tidyr)
library(leaflet)
library(readr)
library(shiny)

# Load custom functions
source("get_data_NCMS.R")

# Time of script running
date_generation <- str_c("Data queried at ", Sys.time(), ".")
```
# 

## 
```{r import_data, message = FALSE, echo = FALSE, results = "hide", cache = TRUE, warning = FALSE}

# Site string
pollutant <- "PM<sub>10</sub>"

# Get data from all the station
time_series_Deira <- get_measurement_time_series("Deira", pollutant)
time_series_Karama <- get_measurement_time_series("Karama", pollutant)
time_series_Zabeel <- get_measurement_time_series("Zabeel", pollutant)
time_series_Safa <- get_measurement_time_series("Safa", pollutant)
time_series_JABELALIVILLAGE <- get_measurement_time_series("JEBEL ALI VILLAGE", pollutant)
time_series_EMIRATESHILLS<- get_measurement_time_series("EMIRATES HILLS", pollutant)
time_series_DUBAIAIRPORT <- get_measurement_time_series("DUBAI AIR PORT", pollutant)
time_series_MUSHRIF <- get_measurement_time_series("MUSHRIF", pollutant)
time_series_Hatta <- get_measurement_time_series("Hatta", pollutant)
time_series_JABELALIPORT <- get_measurement_time_series("JEBEL ALI PORT", pollutant)
time_series_Warsan <- get_measurement_time_series("Warsan", pollutant)
time_series_SHKZAYEDROAD  <- get_measurement_time_series("SHK. ZAYED ROAD", pollutant)
time_series_SHKMOHDBINZAYEDROAD <- get_measurement_time_series("SHK. MOHD. BIN ZAYED ROAD", pollutant)

time_series_ALAinIslamicIns <- get_measurement_time_series("Al Ain Islamic Ins", pollutant)
time_series_ALAinStreet <- get_measurement_time_series("Al Ain Street", pollutant)
time_series_AlMafraq <- get_measurement_time_series("Al Mafraq", pollutant)
time_series_AlQua0x27a <- get_measurement_time_series("Al Qua'a", pollutant)
time_series_AlRuwais <- get_measurement_time_series("Al Ruwais", pollutant)
time_series_AlTawia <- get_measurement_time_series("Al Tawia", pollutant)
time_series_BainAljesrain <- get_measurement_time_series("Bain Al Jesrain", pollutant)
time_series_baniyasSchool <- get_measurement_time_series("Baniyas School", pollutant)
time_series_BidaZayed <- get_measurement_time_series("Bida Zayed", pollutant)
time_series_E11Road <- get_measurement_time_series("E11 Road", pollutant)
time_series_GayathiSchool <- get_measurement_time_series("Gayathi School", pollutant)
time_series_Habshan <- get_measurement_time_series("Habshan", pollutant)
time_series_HamdanStreet <- get_measurement_time_series("Hamdan Street", pollutant)
time_series_KhadejaPrimarySchool <- get_measurement_time_series("Khadeja Primary School", pollutant)
time_series_KhalifaCityA <- get_measurement_time_series("Khalifa City A", pollutant)
time_series_KhalifaHighSchool <- get_measurement_time_series("Khalifa High School", pollutant)
time_series_LiwaOasis <- get_measurement_time_series("Liwa Oasis", pollutant)
time_series_Mussafah <- get_measurement_time_series("Mussafah", pollutant)
time_series_Sweihan <- get_measurement_time_series("Sweihan", pollutant)
time_series_Zakher <- get_measurement_time_series("Zakher", pollutant)

time_series_AlHamriyah <- get_measurement_time_series("Al Hamriyah", pollutant)
time_series_Kalba <- get_measurement_time_series("Kalba", pollutant)
time_series_Rashidyah <- get_measurement_time_series("Rashidyah",pollutant)
time_series_ELdErLyHouse <- get_measurement_time_series("Elderly House", pollutant)
time_series_AlJeer <- get_measurement_time_series("Al Jeer", pollutant)
time_series_Burairat <- get_measurement_time_series("Burairat", pollutant)
time_series_AlQasimiyah <- get_measurement_time_series("Al Qasimiyah", pollutant)
time_series_Ghalilah <- get_measurement_time_series("Ghalilah", pollutant)
```

 `Daily data from all the monitoring stations measuring PM10 and respective values from satellite`
 
# 

## 

```{r plot_NCMS_NO2, echo = FALSE, cache = TRUE}
# Message
date_generation

# Plot
interactive_plot(time_series_Deira, station = "Deira", group = pollutant, pollu= "PM10")
interactive_plot(time_series_Karama, station = "Karama", group = pollutant, pollu= "PM10")
interactive_plot(time_series_Zabeel, station = "Zabeel", group = pollutant, pollu= "PM10")
interactive_plot(time_series_Safa, station = "Safa", group = pollutant, pollu= "PM10")
interactive_plot(time_series_JABELALIVILLAGE, station = "JEBEL ALI VILLAGE", group = pollutant, pollu= "PM10")
interactive_plot(time_series_EMIRATESHILLS, station = "EMIRATES HILLS", group = pollutant, pollu= "PM10")
interactive_plot(time_series_DUBAIAIRPORT, station = "DUBAI AIR PORT", group = pollutant, pollu= "PM10")
interactive_plot(time_series_MUSHRIF, station = "MUSHRIF", group = pollutant, pollu= "PM10")
interactive_plot(time_series_Hatta, station = "Hatta", group = pollutant, pollu= "PM10")
interactive_plot(time_series_JABELALIPORT, station = "JEBEL ALI PORT", group = pollutant, pollu= "PM10")
interactive_plot(time_series_Warsan, station = "Warsan", group = pollutant, pollu= "PM10")
interactive_plot(time_series_SHKZAYEDROAD, station = "SHK. ZAYED ROAD", group = pollutant, pollu= "PM10")
interactive_plot(time_series_SHKMOHDBINZAYEDROAD, station = "SHK. MOHD. BIN ZAYED ROAD", group = pollutant, pollu= "PM10")

interactive_plot(time_series_ALAinIslamicIns, station = "Al Ain Islamic Ins", group =   pollutant, pollu="PM10")
interactive_plot(time_series_ALAinStreet, station = "Al Ain Street", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlMafraq, station = "Al Mafraq", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlQua0x27a, station = "Al Qua'a", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlRuwais, station = "Al Ruwais", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlTawia, station = "Al Tawia", group = pollutant, pollu="PM10")
interactive_plot(time_series_BainAljesrain, station = "Bain Al Jesrain", group = pollutant, pollu="PM10")
interactive_plot(time_series_baniyasSchool, station = "Baniyas School", group = pollutant, pollu="PM10")
interactive_plot(time_series_BidaZayed, station = "Bida Zayed", group = pollutant, pollu="PM10")
interactive_plot(time_series_E11Road, station = "E11 Road", group = pollutant, pollu="PM10")
interactive_plot(time_series_GayathiSchool, station = "Gayathi School", group = pollutant, pollu="PM10")
interactive_plot(time_series_Habshan, station = "Habshan", group = pollutant, pollu="PM10")
interactive_plot(time_series_HamdanStreet, station = "Hamdan Street", group = pollutant, pollu="PM10")
interactive_plot(time_series_KhadejaPrimarySchool, station = "Khadeja Primary School", group = pollutant, pollu="PM10")
interactive_plot(time_series_KhalifaCityA, station = "Khalifa City A", group = pollutant, pollu="PM10")
interactive_plot(time_series_KhalifaHighSchool, station = "Khalifa High School", group =pollutant, pollu="PM10")
interactive_plot(time_series_LiwaOasis, station = "Liwa Oasis", group = pollutant, pollu="PM10")
interactive_plot(time_series_Mussafah, station = "Mussafah", group = pollutant, pollu="PM10")
interactive_plot(time_series_Sweihan, station = "Sweihan", group = pollutant, pollu="PM10")
interactive_plot(time_series_Zakher, station = "Zakher", group = pollutant, pollu="PM10")

interactive_plot(time_series_AlHamriyah, station = "Al Hamriyah", group = pollutant, pollu="PM10")
interactive_plot(time_series_Kalba, station = "Kalba", group = pollutant, pollu="PM10")
interactive_plot(time_series_Rashidyah, station = "Rashidyah", group = pollutant, pollu="PM10")
interactive_plot(time_series_ELdErLyHouse, station = "Elderly House", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlJeer, station = "Al Jeer", group = pollutant, pollu="PM10")
interactive_plot(time_series_Burairat, station = "Burairat", group = pollutant, pollu="PM10")
interactive_plot(time_series_AlQasimiyah, station = "Al Qasimiyah", group = pollutant, pollu="PM10")
interactive_plot(time_series_Ghalilah, station = "Ghalilah", group = pollutant, pollu="PM10")
```


```{r import_data_for_map, message = FALSE, echo = FALSE, results = "hide", cache = TRUE}
# Get site locations

coord_site <- get_sites(var = "PM10")

```
#
 
##

```{r map, fig.height = 8, echo = FALSE, message = FALSE, cache = TRUE}
# Build map
interactive_map(coord_site)
```

 
 